### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by ChristiaanDev** [openPanfu/InformationServer#2]
We need a proper database structure, that is optimized properly with indexes and that stuff. Willing to make it myself on saturday. Let me know if this has been done already so I won't be wasting my time.

**Comment by altro50** [comment]
I've already got one locally, I'll commit it once the GS is done.

**Comment by PanfuLOLIPOP** [comment]
Can you say from when it would be available?

**Comment by jonastisell** [comment]
**@PanfuLOLIPOP** It will probably be available today or tomorrow.

**Comment by altro50** [comment]
Depends on how fast we make the following changes:
- For better laravel support, we decided to change the naming convention (playerId -> player_id).
- Prepare the database for upcoming features.

**Comment by PanfuLOLIPOP** [comment]
nice, do you have discord where you can tell me when it's done?

**Comment by ChristiaanDev** [comment]
Yes, i'm working on it rn. ;)

**Comment by jonastisell** [comment]
**@PanfuLOLIPOP** The discord link is on our project-page http://openpanfu.github.io

**Comment by altro50** [comment]
@PanfuLOLIPOP There's an official discord https://discordapp.com/invite/tJZSrV

**Comment by altro50** [comment]
Database can be created with artisan in the [CMS](https://github.com/openPanfu/CMS).
I will put an SQL file in here once all the tables have been created on there.
