### ISSUE TITLE
API for things like Sessions

### ISSUE THREAD

**Issue by altro50** [openPanfu/InformationServer#4]
This could be useful for CMS writers (like creating a Session ticket for amfConnectionService::doLoginSession).

**Comment by altro50** [comment]
Related to #3

**Comment by ChristiaanDev** [comment]
We could consider creating a CMS in a well documented framework (Laravel) and merging the InformationServer with the CMS. This would make it easy to maintain and easy to develop for. Lmk your opinion on this idea/suggestion.

**Comment by altro50** [comment]
Well, if CMS creators have access to the DB, they might as well set the ticketId, and use that for the session ID that's given in amfConnectionService::doLoginSession.
